// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DataAccess.Schemas.Auth.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expire_date");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("sessions", "auth");
                });

            modelBuilder.Entity("DataAccess.Schemas.Auth.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.DerivationalAffixes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 4, 26, 17, 47, 43, 533, DateTimeKind.Local).AddTicks(3916))
                        .HasColumnName("created_date");

                    b.Property<long>("FirstPartOfSpeachId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FirstPartOfSpeachId");

                    b.Property<bool>("IsSuffix")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsSuffix");

                    b.Property<long>("LastPartOfSpeechId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastPartOfSpeachId");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("FirstPartOfSpeachId");

                    b.HasIndex("LastPartOfSpeechId");

                    b.HasIndex("Title");

                    b.ToTable("derivational_affixes", "public");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.Dialect", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 4, 26, 17, 47, 43, 536, DateTimeKind.Local).AddTicks(1128))
                        .HasColumnName("created_date");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("dialect", "public");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.DialectalDerivationalAffix", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 4, 26, 17, 47, 43, 536, DateTimeKind.Local).AddTicks(3258))
                        .HasColumnName("created_date");

                    b.Property<long>("DerivationalAffixesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DerivationalAffixesId");

                    b.Property<long>("DialectsId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DialectsId");

                    b.Property<bool>("IsSuffix")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsSuffix");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("DerivationalAffixesId");

                    b.HasIndex("DialectsId");

                    b.HasIndex("Title");

                    b.ToTable("dialectal_derivational_affix", "public");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.DialectalInflectionalAffix", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 4, 26, 17, 47, 43, 536, DateTimeKind.Local).AddTicks(5253))
                        .HasColumnName("created_date");

                    b.Property<long>("DialectsId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DialectsId");

                    b.Property<long>("InflectionalAffixesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("InflectionalAffixesId");

                    b.Property<bool>("IsSuffix")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsSuffix");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("DialectsId");

                    b.HasIndex("InflectionalAffixesId");

                    b.HasIndex("Title");

                    b.ToTable("dialectal_inflectional_affix", "public");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.DialectalWord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 4, 26, 17, 47, 43, 536, DateTimeKind.Local).AddTicks(7299))
                        .HasColumnName("created_date");

                    b.Property<long>("DialectsId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DialectsId");

                    b.Property<long>("LiteraryWordsId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LiteraryWordsId");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("DialectsId");

                    b.HasIndex("LiteraryWordsId");

                    b.HasIndex("Title");

                    b.ToTable("dialectal_word", "public");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.InflectionalAffix", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 4, 26, 17, 47, 43, 536, DateTimeKind.Local).AddTicks(9361))
                        .HasColumnName("created_date");

                    b.Property<long>("FirstPartOfSpeachId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FirstPartOfSpeachId");

                    b.Property<bool>("IsSuffix")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsSuffix");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("Title");

                    b.Property<long>("TypesOfInflectionalAffixesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TypesOfInflectionalAffixesId");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("FirstPartOfSpeachId");

                    b.HasIndex("Title");

                    b.HasIndex("TypesOfInflectionalAffixesId");

                    b.ToTable("inflectional_affix", "public");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.LiteraryWord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 4, 26, 17, 47, 43, 537, DateTimeKind.Local).AddTicks(1283))
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("Description");

                    b.Property<long>("PartOfSpeechId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PartOfSpeechId");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("PartOfSpeechId");

                    b.HasIndex("Title");

                    b.ToTable("literary_word", "public");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.PartOfSpeech", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 4, 26, 17, 47, 43, 537, DateTimeKind.Local).AddTicks(3343))
                        .HasColumnName("created_date");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("part_of_speech", "public");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.TypeOfInflectionalAffix", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 4, 26, 17, 47, 43, 537, DateTimeKind.Local).AddTicks(5173))
                        .HasColumnName("created_date");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("type_of_inflectional_affix", "public");
                });

            modelBuilder.Entity("DataAccess.Schemas.Auth.Session", b =>
                {
                    b.HasOne("DataAccess.Schemas.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.DerivationalAffixes", b =>
                {
                    b.HasOne("Dictionary.Domain.Entity.PartOfSpeech", "FirstPartOfSpeach")
                        .WithMany()
                        .HasForeignKey("FirstPartOfSpeachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dictionary.Domain.Entity.PartOfSpeech", "LastPartOfSpeech")
                        .WithMany()
                        .HasForeignKey("LastPartOfSpeechId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstPartOfSpeach");

                    b.Navigation("LastPartOfSpeech");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.DialectalDerivationalAffix", b =>
                {
                    b.HasOne("Dictionary.Domain.Entity.DerivationalAffixes", "DerivationalAffixes")
                        .WithMany()
                        .HasForeignKey("DerivationalAffixesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dictionary.Domain.Entity.Dialect", "Dialects")
                        .WithMany()
                        .HasForeignKey("DialectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DerivationalAffixes");

                    b.Navigation("Dialects");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.DialectalInflectionalAffix", b =>
                {
                    b.HasOne("Dictionary.Domain.Entity.Dialect", "Dialects")
                        .WithMany()
                        .HasForeignKey("DialectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dictionary.Domain.Entity.InflectionalAffix", "InflectionalAffixes")
                        .WithMany()
                        .HasForeignKey("InflectionalAffixesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dialects");

                    b.Navigation("InflectionalAffixes");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.DialectalWord", b =>
                {
                    b.HasOne("Dictionary.Domain.Entity.Dialect", "Dialects")
                        .WithMany()
                        .HasForeignKey("DialectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dictionary.Domain.Entity.LiteraryWord", "LiteraryWords")
                        .WithMany()
                        .HasForeignKey("LiteraryWordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dialects");

                    b.Navigation("LiteraryWords");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.InflectionalAffix", b =>
                {
                    b.HasOne("Dictionary.Domain.Entity.PartOfSpeech", "FirstPartOfSpeach")
                        .WithMany()
                        .HasForeignKey("FirstPartOfSpeachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dictionary.Domain.Entity.TypeOfInflectionalAffix", "TypesOfInflectionalAffixes")
                        .WithMany()
                        .HasForeignKey("TypesOfInflectionalAffixesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstPartOfSpeach");

                    b.Navigation("TypesOfInflectionalAffixes");
                });

            modelBuilder.Entity("Dictionary.Domain.Entity.LiteraryWord", b =>
                {
                    b.HasOne("Dictionary.Domain.Entity.PartOfSpeech", "PartOfSpeech")
                        .WithMany()
                        .HasForeignKey("PartOfSpeechId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartOfSpeech");
                });
#pragma warning restore 612, 618
        }
    }
}
